name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build app
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Deploy to surge
        uses: borales/actions-yarn@v4
        with:
          cmd: surge --token ${{ secrets.SURGE_TOKEN }} --project ./dist --domain mtg-life-counter.surge.sh
